-- Run once in Supabase SQL Editor before deploying. Private backend-only schemas.
BEGIN;

CREATE SCHEMA IF NOT EXISTS converge_replay;

REVOKE ALL ON SCHEMA converge_replay FROM PUBLIC, anon, authenticated;

SET LOCAL search_path = converge_replay;

CREATE TABLE IF NOT EXISTS datasets (
dataset_id TEXT PRIMARY KEY, title TEXT NOT NULL, step INTEGER NOT NULL,
clock TEXT, fixture_json TEXT NOT NULL, excluded_json TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS road_contexts (
dataset_id TEXT NOT NULL REFERENCES datasets(dataset_id) ON DELETE CASCADE,
road_context_id TEXT NOT NULL, payload TEXT NOT NULL,
PRIMARY KEY(dataset_id, road_context_id));
CREATE TABLE IF NOT EXISTS signals (
signal_id TEXT PRIMARY KEY, dataset_id TEXT NOT NULL REFERENCES datasets(dataset_id) ON DELETE CASCADE,
source_family TEXT NOT NULL, source_record_id TEXT NOT NULL, idempotency_key TEXT NOT NULL,
observed_at TEXT NOT NULL, payload TEXT NOT NULL,
UNIQUE(dataset_id, idempotency_key), UNIQUE(dataset_id, source_family, source_record_id));
CREATE INDEX IF NOT EXISTS signals_dataset_time ON signals(dataset_id, observed_at);
CREATE TABLE IF NOT EXISTS evidence (
evidence_id TEXT PRIMARY KEY, signal_id TEXT NOT NULL REFERENCES signals(signal_id) ON DELETE CASCADE,
payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS incidents (
incident_id TEXT PRIMARY KEY, dataset_id TEXT NOT NULL REFERENCES datasets(dataset_id) ON DELETE CASCADE,
revision INTEGER NOT NULL, active INTEGER NOT NULL, review_state TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS incident_revisions (
incident_id TEXT NOT NULL REFERENCES incidents(incident_id) ON DELETE CASCADE,
revision INTEGER NOT NULL, previous_revision INTEGER, snapshot TEXT NOT NULL,
PRIMARY KEY(incident_id, revision));
CREATE TABLE IF NOT EXISTS incident_members (
incident_id TEXT NOT NULL, revision INTEGER NOT NULL,
signal_id TEXT NOT NULL REFERENCES signals(signal_id), capture_group_id TEXT NOT NULL,
reasons TEXT NOT NULL,
PRIMARY KEY(incident_id, revision, signal_id),
FOREIGN KEY(incident_id, revision) REFERENCES incident_revisions(incident_id, revision) ON DELETE CASCADE);

REVOKE ALL ON ALL TABLES IN SCHEMA converge_replay FROM PUBLIC, anon, authenticated;

CREATE SCHEMA IF NOT EXISTS converge_live;

REVOKE ALL ON SCHEMA converge_live FROM PUBLIC, anon, authenticated;

SET LOCAL search_path = converge_live;

CREATE TABLE IF NOT EXISTS datasets (
dataset_id TEXT PRIMARY KEY, title TEXT NOT NULL, step INTEGER NOT NULL,
clock TEXT, fixture_json TEXT NOT NULL, excluded_json TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS road_contexts (
dataset_id TEXT NOT NULL REFERENCES datasets(dataset_id) ON DELETE CASCADE,
road_context_id TEXT NOT NULL, payload TEXT NOT NULL,
PRIMARY KEY(dataset_id, road_context_id));
CREATE TABLE IF NOT EXISTS signals (
signal_id TEXT PRIMARY KEY, dataset_id TEXT NOT NULL REFERENCES datasets(dataset_id) ON DELETE CASCADE,
source_family TEXT NOT NULL, source_record_id TEXT NOT NULL, idempotency_key TEXT NOT NULL,
observed_at TEXT NOT NULL, payload TEXT NOT NULL,
UNIQUE(dataset_id, idempotency_key), UNIQUE(dataset_id, source_family, source_record_id));
CREATE INDEX IF NOT EXISTS signals_dataset_time ON signals(dataset_id, observed_at);
CREATE TABLE IF NOT EXISTS evidence (
evidence_id TEXT PRIMARY KEY, signal_id TEXT NOT NULL REFERENCES signals(signal_id) ON DELETE CASCADE,
payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS incidents (
incident_id TEXT PRIMARY KEY, dataset_id TEXT NOT NULL REFERENCES datasets(dataset_id) ON DELETE CASCADE,
revision INTEGER NOT NULL, active INTEGER NOT NULL, review_state TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS incident_revisions (
incident_id TEXT NOT NULL REFERENCES incidents(incident_id) ON DELETE CASCADE,
revision INTEGER NOT NULL, previous_revision INTEGER, snapshot TEXT NOT NULL,
PRIMARY KEY(incident_id, revision));
CREATE TABLE IF NOT EXISTS incident_members (
incident_id TEXT NOT NULL, revision INTEGER NOT NULL,
signal_id TEXT NOT NULL REFERENCES signals(signal_id), capture_group_id TEXT NOT NULL,
reasons TEXT NOT NULL,
PRIMARY KEY(incident_id, revision, signal_id),
FOREIGN KEY(incident_id, revision) REFERENCES incident_revisions(incident_id, revision) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS extraction_cache(cache_key TEXT PRIMARY KEY, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS api_usage(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, model TEXT, role TEXT,
started_at TEXT, input_tokens INTEGER, output_tokens INTEGER, reserved_usd DOUBLE PRECISION,
estimated_usd DOUBLE PRECISION, outcome TEXT, response_ref TEXT, task TEXT NOT NULL DEFAULT 'text');
CREATE TABLE IF NOT EXISTS cache_events(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, at TEXT, cache_key TEXT,
task TEXT NOT NULL DEFAULT 'text');
CREATE TABLE IF NOT EXISTS raw_text_responses(response_ref TEXT PRIMARY KEY, model TEXT,
status TEXT, received_at TEXT, output_text TEXT);
CREATE TABLE IF NOT EXISTS raw_responses(response_ref TEXT PRIMARY KEY, model TEXT, role TEXT,
status TEXT, received_at TEXT, output_text TEXT);

CREATE TABLE IF NOT EXISTS text_jobs(signal_id TEXT PRIMARY KEY, original_json TEXT NOT NULL,
status TEXT NOT NULL, error_code TEXT, revision INTEGER NOT NULL DEFAULT 0,
linked_image_signal_id TEXT);
CREATE TABLE IF NOT EXISTS extraction_revisions(signal_id TEXT NOT NULL, revision INTEGER NOT NULL,
payload TEXT NOT NULL, PRIMARY KEY(signal_id,revision));

CREATE TABLE IF NOT EXISTS image_jobs(
signal_id TEXT PRIMARY KEY, original_json TEXT NOT NULL,
status TEXT NOT NULL, error_code TEXT, revision INTEGER NOT NULL DEFAULT 0,
linked_text_signal_id TEXT, raw_hash TEXT NOT NULL, stored_path TEXT NOT NULL,
normalization_json TEXT NOT NULL, perceptual_hash TEXT);

REVOKE ALL ON ALL TABLES IN SCHEMA converge_live FROM PUBLIC, anon, authenticated;

COMMIT;
