"""PostgreSQL transport for the existing SQL store, without changing payloads."""
import os
import re
import tempfile
from contextlib import contextmanager
from pathlib import Path
from threading import local
from urllib.parse import urlsplit

import psycopg

from .store import Store


def connection_options(url):
    try:
        parsed = urlsplit(url)
        if parsed.scheme not in {"postgres", "postgresql"} or not parsed.hostname or not parsed.path.strip("/"):
            raise ValueError
        parsed.port
    except ValueError:
        raise ValueError("DATABASE_URL must be a PostgreSQL connection URL") from None
    return {"conninfo": url, "prepare_threshold": None, "connect_timeout": 10,
            "sslmode": "require"}


class Row(dict):
    def __getitem__(self, key):
        return tuple(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


def row_factory(cursor):
    names = [column.name for column in cursor.description] if cursor.description else []
    return lambda values: Row(zip(names, values))


def portable_sql(sql):
    # Only the fixed SQL used by this repository; values remain bound parameters.
    sql = sql.replace("?", "%s")
    sql = sql.replace("id INTEGER PRIMARY KEY", "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    sql = re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)
    sql = re.sub(r"sum\(([^()]*=[^()]*)\)", r"sum(CASE WHEN \1 THEN 1 ELSE 0 END)", sql)
    if "INSERT OR REPLACE INTO extraction_cache" in sql:
        sql = sql.replace("INSERT OR REPLACE", "INSERT") + " ON CONFLICT(cache_key) DO UPDATE SET payload=excluded.payload"
    if "INSERT OR IGNORE" in sql:
        sql = sql.replace("INSERT OR IGNORE", "INSERT") + " ON CONFLICT DO NOTHING"
    return sql


class Connection:
    def __init__(self, db, schema):
        self.db, self.schema = db, schema

    def execute(self, sql, parameters=()):
        if sql == "BEGIN IMMEDIATE":
            # connection() already holds the transaction-scoped database lock.
            return self.db.execute("SELECT 1")
        match = re.fullmatch(r"PRAGMA table_info\((\w+)\)", sql)
        if match:
            return self.db.execute("SELECT ordinal_position, column_name FROM information_schema.columns "
                                   "WHERE table_schema=%s AND table_name=%s ORDER BY ordinal_position",
                                   (self.schema, match[1]))
        if sql == "PRAGMA foreign_keys":
            return self.db.execute("SELECT 1")  # PostgreSQL always enforces declared FKs.
        converted = portable_sql(sql)
        if sql.startswith("INSERT INTO api_usage("):
            cursor = self.db.execute(converted + " RETURNING id", parameters)
            return type("Inserted", (), {"lastrowid": cursor.fetchone()[0]})()
        return self.db.execute(converted, parameters)

    def executemany(self, sql, parameters):
        with self.db.cursor() as cursor:
            cursor.executemany(portable_sql(sql), parameters)

    def executescript(self, script):
        for statement in script.split(";"):
            if statement.strip():
                self.execute(statement.strip())


class TransactionLock:
    """Reentrant across store calls, with one transaction per outer operation."""
    def __init__(self, store):
        self.store = store
        self.state = local()

    def __enter__(self):
        context = self.store.connection()
        context.__enter__()
        if not hasattr(self.state, "stack"):
            self.state.stack = []
        self.state.stack.append(context)
        return self

    def __exit__(self, *error):
        return self.state.stack.pop().__exit__(*error)


class PostgresStore(Store):
    backend = "postgres"

    def __init__(self, path=None, *, namespace="replay"):
        if namespace not in {"replay", "live"}:
            raise ValueError("Invalid storage namespace")
        self.schema = "converge_" + namespace
        self.options = connection_options(os.environ["DATABASE_URL"].strip())
        # Image decoding only. Required bytes are stored in Supabase Storage.
        self.path = Path(tempfile.gettempdir()) / "converge" / "converge.sqlite3"
        self.state_local = local()
        self.lock = TransactionLock(self)
        # Bootstrap is explicit SQL, never DDL on concurrent function cold starts.

    def live_store(self):
        return Store(namespace="live")

    @contextmanager
    def connection(self):
        existing = getattr(self.state_local, "connection", None)
        if existing is not None:
            yield existing
            return
        with psycopg.connect(**self.options, row_factory=row_factory) as db:
            db.execute("SELECT pg_advisory_xact_lock(%s)",
                       (746210 if self.schema == "converge_replay" else 746211,))
            db.execute("SELECT set_config('search_path', %s, true)", (self.schema,))
            self.state_local.connection = Connection(db, self.schema)
            try:
                yield self.state_local.connection
            finally:
                self.state_local.connection = None
